Save sourceMap if returned from scss
thgh/rollup-plugin-scss pull request #66
Opened 2021-01-06 17:15 UTC by astappiev

This change allows saving source map near compiled .css file.

To make it work, the compiler should return not empty map (by default it is empty).
To make it not empty, we should pass `sourceMap` and `outFile` options to `sass.renderSync` method.

The `outFile` is added automatically in this PR, and `sourceMap`  should be given by a user, like:
```js
scss({
  sourceMap: true,
})
```

2021-02-07 13:51 UTC, thgh requested changes
Awesome, can you add a test for this?

2021-02-07 17:49 UTC, astappiev commented
Done

2021-02-16 12:56 UTC, christian-beckmann commented
When does this go online/released?

2021-02-17 11:04 UTC, thgh reviewed
Hi, this PR makes a lot of changes which makes it tough to merge at once, I hope to merge all PRs in the coming weeks.

2021-02-17 11:04 UTC, thgh commented on README.md
> -  processor: css => css.replace('/*date*/', '/* ' + new Date().toJSON() + ' */'),
Can we make this backwards-compatible? => if processor returns a string, it's css; otherwise like above.

2021-02-19 08:27 UTC, merged